# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    gulp default --gulpfile gulpfile.js
    gulp build --ship
    gulp bundle --ship
    gulp package-solution --ship
    dir
  displayName: 'npm install and run gulp'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/sharepoint/solution'
    Contents: 'spfx-first-sarath.sppkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
